apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ktu679oaq-python 
  janus-idp.io/tekton: ktu679oaq-python
  backstage.io/kubernetes-id: ktu679oaq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ktu679oaq-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  