apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ktu679oaq-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/ktu679oaq-python-gitops